pipeline {
    agent any

    stages {

        stage('Setup Python') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Test') {
            steps {
                sh '''
                . venv/bin/activate
                mkdir -p artifacts
                PYTHONPATH=src python src/run.py --headless
                '''
            }
        }

        stage('Archive Report') {
            steps {
                archiveArtifacts artifacts: 'artifacts/*', allowEmptyArchive: true
            }
        }
    }
}